- hosts: localhost
  gather_facts: false
  vars:
    vault_cluster: nerc-ocp-infra
    cluster_names:
      - "{{ vault_cluster }}"
      - nerc-ocp-prod
      - nerc-ocp-test
    vault_groups:
      - name: nerc-ops
        policy: nerc-all-writer
      - name: vault-admins
        policy: admin
      - name: nerc-org-admins
        policy: admin
  tasks:
    - name: Avoid trying to change the wrong vault instance
      fail:
        msg: "Incorrect vault credentials"
      when: >-
        vault_cluster not in lookup("env", "VAULT_ADDR")

    - name: Configure secret engine
      tags: [vault-kv2-store]
      include_role:
        name: vault-kv2-store
        apply:
          tags: vault-kv2-store
      vars:
        secret_store_path: nerc

    - name: Configure global policies
      tags: [vault-common-policy]
      include_role:
        name: vault-common-policy
        apply:
          tags: vault-common-policy

    - name: Install per-cluster policies
      tags: [vault-cluster-policy]
      include_role:
        name: vault-cluster-policy
        apply:
          tags: [vault-cluster-policy]
      loop: "{{ cluster_names }}"
      loop_control:
        loop_var: cluster_name

    - name: Configure auth for internal cluster
      tags: [vault-kubernetes-auth]
      include_role:
        name: vault-kubernetes-auth
        apply:
          tags: [vault-kubernetes-auth]
      vars:
        cluster_name: nerc-ocp-infra
        kubernetes_service_account_namespaces: external-secrets-operator

    - name: Configure auth for prod cluster
      tags: [vault-kubernetes-auth]
      include_role:
        name: vault-kubernetes-auth
        apply:
          tags: [vault-kubernetes-auth]
      vars:
        cluster_name: nerc-ocp-prod
        kubernetes_host: https://api.nerc-ocp-prod.rc.fas.harvard.edu:6443
        kubernetes_service_account_namespaces: openshift-config,openshift-ingress-operator,openshift-logging
        kubernetes_service_account_names: vault-secret-reader
        kubernetes_token_reviewer_jwt: "{{ lookup('token/nerc-ocp-prod.jwt') }}"

    - name: Configure oidc auth
      tags: [vault-oidc-auth]
      include_role:
        name: vault-oidc-auth
        apply:
          tags: [vault-oidc-auth]
      vars:
        oidc_discovery_url: "https://dex-dex.apps.nerc-ocp-infra.rc.fas.harvard.edu"
        oidc_redirect_uris: "https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/auth/oidc/oidc/callback"
        oidc_secret_mount: "nerc"
        oidc_client_secret_path: "nerc-ocp-infra/dex/dex-clients"
        oidc_client_secret_key: "VAULT_SECRET"

    - name: Create groups
      tags: [vault-group]
      include_role:
        name: vault-group
        apply:
          tags: [vault-group]
      vars:
        group_name: "{{ item.name }}"
        group_policy: "{{ item.policy }}"
      loop: "{{ vault_groups }}"
