- hosts: localhost
  gather_facts: false
  vars:
    vault_cluster: nerc-ocp-infra
    cluster_names:
      - "{{ vault_cluster }}"
      - nerc-ocp-prod
      - nerc-ocp-test
  tasks:
    - name: Avoid being a dum dum
      fail:
        msg: "Incorrect vault credentials"
      when: >-
        vault_cluster not in lookup("env", "VAULT_ADDR")

    - name: Get enabled secret stores
      command: >-
        vault secrets list -format json
      register: enabled_stores

    - name: Create secret store
      command: >-
        vault secrets enable -version=2 -path "nerc" kv
      when: >-
        "nerc/" not in (enabled_stores.stdout|from_json)

    - name: Install common policies
      command: >-
        vault policy write "{{ (item|basename|splitext)[0] }}" "{{ item }}"
      loop: "{{ query('fileglob', 'common_policies/*.hcl') }}"

    - name: Install per-cluster policies
      tags: [vault-cluster-policy]
      include_role:
        name: vault-cluster-policy
      loop: "{{ cluster_names }}"
      loop_control:
        loop_var: cluster_name

    - name: Configure auth for internal cluster
      tags: [vault-kubernetes-auth]
      include_role:
        name: vault-kubernetes-auth
      vars:
        cluster_name: nerc-ocp-infra
