- hosts: localhost
  gather_facts: false
  vars:
    vault_cluster: nerc-ocp-infra
    cluster_names:
      - "{{ vault_cluster }}"
      - nerc-ocp-prod
      - nerc-ocp-test
  tasks:
    - name: Avoid trying to change the wrong vault instance
      fail:
        msg: "Incorrect vault credentials"
      when: >-
        vault_cluster not in lookup("env", "VAULT_ADDR")

    - import_role:
        name: vault-secret-store
      tags: [vault-secret-store]
      vars:
        secret_store_path: nerc

    - tags: [vault-common-policy]
      import_role:
        name: vault-common-policy

    - name: Install per-cluster policies
      tags: [vault-cluster-policy]
      include_role:
        name: vault-cluster-policy
      loop: "{{ cluster_names }}"
      loop_control:
        loop_var: cluster_name

    - name: Configure auth for internal cluster
      tags: [vault-kubernetes-auth]
      include_role:
        name: vault-kubernetes-auth
      vars:
        cluster_name: nerc-ocp-infra

    - name: Configure oidc auth
      tags: [vault-oidc-auth]
      import_role:
        name: vault-oidc-auth
      vars:
        oidc_discovery_url: https://dex-dex.apps.nerc-ocp-infra.rc.fas.harvard.edu
        oidc_redirect_uris: "https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/auth/oidc/oidc/callback"
        oidc_client_secret_path: nerc/nerc-ocp-infra/dex/dex-clients
        oidc_client_secret_key: VAULT_SECRET
