- name: Get enabled secret stores
  command: >-
    vault secrets list -format json
  register: enabled_stores

- name: Create secret store
  command: >-
    vault secrets enable -version=2 -path "{{ secret_store_path }}" kv
  when: >-
    "{}/".format(secret_store_path) not in (enabled_stores.stdout|from_json)
