- name: "{{ cluster_name }}: Install policies"
  community.hashi_vault.vault_write:
    token_validate: false
    path: "sys/policy/{{ policyname }}"
    data:
      name: "{{ policyname }}"
      rules: "{{ lookup('template', item) }}"
  vars:
    policyname: "{{ cluster_name }}-{{ item|basename|split('.')|first }}"
  loop: "{{ query('fileglob', 'templates/policies/*.hcl') }}"
  loop_control:
    label: "{{ policyname }}"
