- name: "{{ config_path }} : Render jsonnet template"
  command: jsonnet -J lib -J data {{ config_path }}
  changed_when: false
  no_log: true
  register: rendered_config

- name: "{{ config_path }} : Unmarshal vault configuration"
  set_fact:
    config: "{{ rendered_config.stdout | from_json }}"

- name: "{{ config_path }} : Cache rendered template for inspection"
  copy:
    content: "{{ config | to_nice_yaml }}"
    dest: "rendered/{{ (config_path | replace('/', '_') | splitext)[0] }}.yaml"

- name: "{{ config_path }} : Check for existing resources"
  when: >
    item['if-not-exists'] | default(false)
  uri:
    url: "{{ vault_addr }}{{ item.path }}"
    method: GET
    headers:
      x-vault-token: "{{ vault_token }}"
    status_code: [200, 404]
  register: exists
  loop: "{{ config.resources }}"
  loop_control:
    label: "{{ item.path }}"

- name: "{{ config_path }} : Apply configuration"
  tags: [apply]
  uri:
    url: "{{ vault_addr }}{{ item.item.path }}"
    method: POST
    headers:
      x-vault-token: "{{ vault_token }}"
    body_format: json
    body: "{{ item.item.payload }}"
    status_code: [200,204]
  when: >
    item.skipped|default(false) or item.status == 404
  loop: "{{ exists.results }}"
  loop_control:
    label: "{{ item.item.path }}"
