- name: "{{ cluster_name }}: Get enabled auth methods"
  tags: [vault-approle-auth, auth]
  command: >-
    vault auth list -format json
  changed_when: false
  register: auths_enabled

- name: "{{ cluster_name }}: Enable approle auth"
  tags: [vault-approle-auth, auth]
  command: >-
    vault auth enable -path approle/{{ cluster_name }} approle
  when: >-
    "approle/{}/".format(cluster_name) not in (auths_enabled.stdout|from_json)

- name: "{{ cluster_name }}: Get roles"
  tags: [vault-approle-auth, role]
  command: >-
    vault list -format json auth/approle/{{ cluster_name }}/role
  changed_when: false
  failed_when: roles.rc not in [0, 2]
  register: roles

- name: "{{ cluster_name }}: Create role for clustersecretstore"
  tags: [vault-approle-auth, role]
  command: >-
    vault write auth/approle/{{ cluster_name }}/role/nerc-secret-reader
        policies={{ cluster_name }}-reader
  when: >-
    "{}-reader".format(cluster_name) not in (roles.stdout|from_json)
