- name: "{{ cluster_name }}: check if auth method is enabled"
  community.hashi_vault.vault_read:
    token_validate: false
    path: /sys/auth
  register: auths
  changed_when: >-
    "kubernetes/{}/".format(cluster_name) not in auths.data

- name: "{{ cluster_name }}: enable kubernetes auth"
  when: >-
    auths is changed
  community.hashi_vault.vault_write:
    token_validate: false
    path: "/sys/auth/kubernetes/{{ cluster_name }}"
    data:
      type: kubernetes

- name: "{{ cluster_name }}: configure kubernetes auth"
  community.hashi_vault.vault_write:
    token_validate: false
    path: "/auth/kubernetes/{{ cluster_name }}/config"
    data:
      kubernetes_host: "{{ kubernetes_host }}"
      token_reviewer_jwt: "{{ kubernetes_token_reviewer_jwt|default(omit) }}"

- name: "{{ cluster_name }}: configure role for clustersecretstore"
  community.hashi_vault.vault_write:
    token_validate: false
    path: "/auth/kubernetes/{{ cluster_name }}/role/secret-reader"
    data:
      policies: "{{ cluster_name }}-reader"
      bound_service_account_names: "{{ kubernetes_service_account_names }}"
      bound_service_account_namespaces: "{{ kubernetes_service_account_namespaces }}"
